name: R
channels:
  - conda-forge
  - bioconda
dependencies:
  - r-base=4.3.1
  - r-rmarkdown
  - r-doParallel
  - r-seurat
  - r-signac
  - r-pheatmap
  - r-mclust
  - r-openxlsx
  - r-HGNChelper
  - r-dplyr
  - r-igraph
  - r-openxlsx
  - r-ggplot2
  - r-ggpubr
  - r-ggVennDiagram
  - r-pheatmap
  - r-devtools
  - r-UpSetR
  - bioconductor-limma
  - bioconductor-glmGamPoi
  - bioconductor-fishpond
  - bioconductor-BSgenome
  - bioconductor-Biostrings
  - bioconductor-GenomicFeatures
  - bioconductor-GenomicRanges
  - bioconductor-SingleCellExperiment
